// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.DiamondModels
{
    public partial class DiamondCheck
    {
        public DiamondCheck()
        {
            DiamondCheckValues = new HashSet<DiamondCheckValue>();
        }

        public int DiamondCheckId { get; set; }
        public string CertificateId { get; set; }
        public string Origin { get; set; }
        public string Shape { get; set; }
        public double? Carat { get; set; }
        public string Color { get; set; }
        public string Clarity { get; set; }
        public string Fluorescence { get; set; }
        public string Symmetry { get; set; }
        public string Polish { get; set; }
        public string CutGrade { get; set; }
        public string CutScore { get; set; }
        public DateTime? CertDate { get; set; }
        public string Measurement { get; set; }
        public string ClarityCharacteristic { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }

        public virtual ICollection<DiamondCheckValue> DiamondCheckValues { get; set; }
    }
}