// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Data.DiamondModels
{
    public partial class SWP391_DiamondSystemContext : DbContext
    {
        public SWP391_DiamondSystemContext()
        {
        }

        public SWP391_DiamondSystemContext(DbContextOptions<SWP391_DiamondSystemContext> options)
            : base(options)
        {
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
=> optionsBuilder.UseSqlServer("data source=diavan-valuation.asia;initial catalog=SWP391_DiamondSystem;user id=sa;password=<YourStrong@Passw0rd>;trustservercertificate=true;multipleactiveresultsets=true;");
        public virtual DbSet<Diamond> Diamonds { get; set; }
        public virtual DbSet<DiamondCheck> DiamondChecks { get; set; }
        public virtual DbSet<DiamondCheckValue> DiamondCheckValues { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Diamond>(entity =>
            {
                entity.ToTable("Diamond");

                entity.Property(e => e.Status).IsRequired();
            });

            modelBuilder.Entity<DiamondCheck>(entity =>
            {
                entity.ToTable("DiamondCheck");

                entity.Property(e => e.Status).IsRequired();
            });

            modelBuilder.Entity<DiamondCheckValue>(entity =>
            {
                entity.ToTable("DiamondCheckValue");

                entity.HasOne(d => d.DiamondCheck)
                    .WithMany(p => p.DiamondCheckValues)
                    .HasForeignKey(d => d.DiamondCheckId);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}