// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.DiavanModels
{
    public partial class AssigningOrderDetail
    {
        public int Id { get; set; }
        public int ValuationStaffId { get; set; }
        public int? ResultId { get; set; }
        public string Status { get; set; }
        public DateTime DayCreate { get; set; }
        public int OrderDetailid { get; set; }

        public virtual OrderDetail OrderDetail { get; set; }
        public virtual Result Result { get; set; }
        public virtual Account ValuationStaff { get; set; }
    }
}