// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.DiavanModels
{
    public partial class Order
    {
        public Order()
        {
            OrderDetails = new HashSet<OrderDetail>();
        }

        public int OrderId { get; set; }
        public string Code { get; set; }
        public int CustomerId { get; set; }
        public DateTime Time { get; set; }
        public int? Quantity { get; set; }
        public double? TotalPay { get; set; }
        public string Payment { get; set; }
        public string StatusPayment { get; set; }
        public string Status { get; set; }
        public DateTime? CompleteDate { get; set; }
        public DateTime? ExpireDate { get; set; }
        public int? ConsultingStaffId { get; set; }
        public DateTime? ReceiveDay { get; set; }

        public virtual Account ConsultingStaff { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}