// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.DiavanModels
{
    public partial class ServiceDetail
    {
        public int ServiceDetailId { get; set; }
        public string Code { get; set; }
        public double MinRange { get; set; }
        public double MaxRange { get; set; }
        public double Price { get; set; }
        public double ExtraPricePerMm { get; set; }
        public string Status { get; set; }
        public int ServiceId { get; set; }

        public virtual Service Service { get; set; }
    }
}